commit 4

diff --git a/.github/workflows/lesson1.yaml b/.github/workflows/lesson1.yaml
--- a/.github/workflows/lesson1.yaml
+++ b/.github/workflows/lesson1.yaml
@@ -5,8 +5,10 @@ jobs:
   first_job:
     runs-on: ubuntu-latest
     steps:
-      - name: step1
-        run: echo "Hello first job today"
+      - name: failurestep
+        run: | 
+          echo "I will fail"
+          exit 1
 
   second_job:
     runs-on: ubuntu-latest
